# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=20)),
                ('Query', models.CharField(default='', max_length=40)),
                ('MarketCap', models.FloatField(default=0)),
                ('Profit', models.FloatField(default=0)),
                ('MPRatio', models.FloatField(default=0)),
                ('PE', models.FloatField(default=0)),
                ('EMS', models.FloatField(default=0)),
                ('Bid', models.FloatField(default=0)),
                ('Offer', models.FloatField(default=0)),
                ('Spread', models.FloatField(default=0)),
                ('Dividend', models.FloatField(default=0)),
                ('NetDebt', models.FloatField(default=0)),
                ('Liquidity', models.FloatField(default=0)),
                ('DPRatio', models.FloatField(default=0)),
                ('ProfitTrend', models.FloatField(default=0)),
                ('DividendTrend', models.FloatField(default=0)),
                ('DebtTrend', models.FloatField(default=0)),
                ('Price', models.FloatField(default=0)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open', models.FloatField(default=0)),
                ('Close', models.FloatField(default=0)),
                ('High', models.FloatField(default=0)),
                ('Low', models.FloatField(default=0)),
                ('Volumn', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Stock')),
            ],
        ),
    ]
