# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
