# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Catagory',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='Sector',
            field=models.CharField(default='', max_length=200),
        ),
    ]
