# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20160127_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_change', models.FloatField(default=0)),
                ('monthly_change', models.FloatField(default=0)),
                ('seasonally_change', models.FloatField(default=0)),
                ('halfyearly_change', models.FloatField(default=0)),
                ('yearly_change', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Stock')),
            ],
        ),
    ]
