# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20160219_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='update_date',
            new_name='pub_date',
        ),
    ]
