# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_stocknews'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('target', models.FloatField(default=0)),
                ('stop', models.FloatField(default=0)),
                ('sell', models.FloatField(default=0)),
                ('pl', models.FloatField(default=0)),
                ('buy_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sell_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Stock')),
            ],
        ),
    ]
