# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_stocknt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorhistory',
            name='Sector',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sectorhistory',
            name='Symbol',
            field=models.CharField(default='', max_length=20),
        ),
    ]
